### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by TheKnarf** [sanity-io/groq-js#13]
There doesn't seem to be a LICENSE / COPYING file in the project, nor does it look like the license field in package.json is set.

The Readme does mention the license but it would be nice if there was both a LICENSE file as well as the appropriate field in package.json.

**Comment by judofyr** [comment]
Thanks for the report! I've added a `LICENSE.md` in addition to setting `"license":"MIT"` in package.json.

(Note: In the commit above I managed to copy an incorrect license text, but the correct one has been fixed in 4070e7364ffb02cc8e4dedf9dff15b3a4e6b6d9b).
