### ISSUE TITLE
Missing feature: string concatenation

### ISSUE THREAD

**Issue by elimisteve** [sanity-io/groq-js#15]
This works:

```bash
$ curl -s http://api.nobelprize.org/v1/laureate.json | jq .laureates | groq '*[gender == "female" && "physics" in prizes[].category]{firstname, surname}' --pretty
```

I'm pretty sure that the very similar query (with string concatenation of `firstname` and `surname`)

```bash
$ curl -s http://api.nobelprize.org/v1/laureate.json | jq .laureates | groq '*[gender == "female" && "physics" in prizes[].category]{firstname + surname}' --pretty
```

should work as per https://www.sanity.io/docs/query-cheat-sheet#arithmetic-and-concatenation-5a9dcaf4e63e . I'm not sure if the following should work but it'd be _great_ if it did (string concat with space in between):

```
$ curl -s http://api.nobelprize.org/v1/laureate.json | jq .laureates | groq '*[gender == "female" && "physics" in prizes[].category]{firstname + " " + surname}' --pretty
```

T'would be great to add this. Thanks!

**Comment by judofyr** [comment]
There's actually a different issue here, and I'm sorry for the poor error message. The problem is that when you use `{}` you need to explicitly decide a key when there's a complicated expression. The following works:

```
$ curl -s http://api.nobelprize.org/v1/laureate.json | jq .laureates | groq '*[gender == "female" && "physics" in prizes[].category]{"name": firstname + " " + surname}' --pretty
```

`{firstname}` is a shortcut for `{"firstname": firstname}` and these types of shortcuts only work on the most basic expressions.

**Comment by elimisteve** [comment]
Makes sense! Thank you.

**Comment by dnlmzw** [comment]
Any way to concatenate a string with a number? Have a product ID and SKU that I want to combine into one. However, it doesn't seem possible when they're of different types.

```
const SKU = 'ABC213'
const ID = 123456
```

Query
```
*[_type == "product"] {"ID": productID + " " + sku}
```

**Comment by dnlmzw** [comment]
[I found this](https://github.com/sanity-io/sanity/issues/1108)

However, when using `string(productID)` on `6809646170320` I get this in return `16043_6.80964617032e+12`.

Might just be a bug.
