### ISSUE TITLE
GROQ `| order(name asc)` sorts uppercase then lowercase e.g. ABGc not ABcG

### ISSUE THREAD

**Issue by simonhrogers** [sanity-io/groq-js#167]
I’m not sure if this is a bug; but it’s not what I would expect personally. Is there a logic for this decision that makes sense in other contexts/cultures/languages? I’m doing in the limited context of ordering a list of ‘collaborator’ documents alphabetically. It’s important they’re alphabetised irrespective of case because some people use lowercase as a stylistic decision but you’d still expect to find them listed under ‘c’. 

To be clear, current order sorted by GROQ is:

```
A
Akera Engineers

G
Gardiner and Theobald
Gerald Eve

C
cc|be
```

But I would expect:

```
A
Akera Engineers

C
cc|be

G
Gardiner and Theobald
Gerald Eve
```

**Comment by hacknug** [comment]
> I’m not sure if this is a bug

Me neither but I think you can use [`global::lower()`](https://sanity-io.github.io/GROQ/draft/#sec-global-lower-) to sort the lowercase string instead.

**Comment by judofyr** [comment]
This is not a bug: The ordering is based on the Unicode codepoint and is not aware of locale or anything like that. It's maybe not the most useful behavior, but it's quite easy to reason about.

For this specific case, as @hacknug mentioned, you can use `lower`:

```
*[_type == "post"]|order(lower(title))
```
