### ISSUE TITLE
Bracket syntax fails

### ISSUE THREAD

**Issue by fabien** [sanity-io/groq-js#43]
This doesn't work, even though it works fine in Sanity itself:

https://groq.dev/2PvDBM3KG6OJXWIvHguRSe

Be sure to set the params to `{ "locale": "english" }` for example.

**Comment by judofyr** [comment]
`groq.dev` isn't quite up-to-date with the latest version of groq-js. For this to work correctly in the latest version of groq-js you'll have to pass the parameters to both `parse` and `evaluate`:

```js
const params = { locale: "english" }
const tree = parse(groq`*[]{
  'name': coalesce(name[$locale], 'not found')
}`, {params});
const result = evaluate(tree, {params})
```

I'll see if I can update groq.dev to the latest version.
