### ISSUE TITLE
Accept different dataset names

### ISSUE THREAD

**Issue by marekbrze** [sanity-io/groq-js#50]
Right now the only acceptable name for the data is `dataset`. It would be much more useful to accept other names. 

Usign `let dataset` works as expected:
```
...
let dataset = await fs.readJson("./places.json");
...
let value = await evaluate(tree, { dataset });
```

Using `let places` doesn't work:
```
...
let places = await fs.readJson("./places.json");
...
let value = await evaluate(tree, { places });
```

This will help to call data that is already available. 

---

Below is the example code with changed dataset name. It doesn't work and returns `null`:

```
import { parse, evaluate } from "groq-js";

let input = `*[_type == 'user']{name}`;

let dataset2 = [
  { _type: "user", name: "Michael" },
  { _type: "company", name: "Bluth Company" },
];

// Returns an ESTree-inspired syntax tree
let tree = parse(input);

// Evaluate a tree against a dataset
let value = await evaluate(tree, { dataset2 });

// Gather everything into one JavaScript object
let result = await value.get();

console.log(result);
```

**Comment by judofyr** [comment]
As @alfrdmalr is mentioning, `await evaluate(tree, { dataset: places });` is the way to go if you want to use a different local variable.
